package com.android.settingslib.mobile;

import android.icu.text.DateFormat;
import androidx.core.p004os.EnvironmentCompat;
import com.android.settingslib.AccessibilityContentDescriptions;
import com.android.settingslib.C1757R;
import com.android.settingslib.SignalIcon;
import com.google.android.setupcompat.logging.internal.FooterBarMixinMetrics;
import java.util.HashMap;
import java.util.Map;

public class TelephonyIcons {
    public static final SignalIcon.MobileIconGroup CARRIER_MERGED_WIFI;
    public static final SignalIcon.MobileIconGroup CARRIER_NETWORK_CHANGE;
    public static final SignalIcon.MobileIconGroup DATA_DISABLED;

    /* renamed from: E */
    public static final SignalIcon.MobileIconGroup f249E;
    public static final SignalIcon.MobileIconGroup FIVE_G;
    public static final SignalIcon.MobileIconGroup FIVE_G_BASIC;
    public static final SignalIcon.MobileIconGroup FIVE_G_SA;
    public static final SignalIcon.MobileIconGroup FIVE_G_UWB;
    public static final int FLIGHT_MODE_ICON = C1757R.C1759drawable.stat_sys_airplane_mode;
    public static final SignalIcon.MobileIconGroup FOUR_G;
    public static final SignalIcon.MobileIconGroup FOUR_G_LTE;
    public static final SignalIcon.MobileIconGroup FOUR_G_LTE_PLUS;
    public static final SignalIcon.MobileIconGroup FOUR_G_PLUS;

    /* renamed from: G */
    public static final SignalIcon.MobileIconGroup f250G;

    /* renamed from: H */
    public static final SignalIcon.MobileIconGroup f251H;
    public static final SignalIcon.MobileIconGroup H_PLUS;
    public static final int ICON_1X;
    public static final int ICON_3G;
    public static final int ICON_4G;
    public static final int ICON_4G_LTE;
    public static final int ICON_4G_LTE_PLUS;
    public static final int ICON_4G_PLUS;
    public static final int ICON_5G;
    public static final int ICON_5G_BASIC;
    public static final int ICON_5G_E;
    public static final int ICON_5G_PLUS;
    public static final int ICON_5G_SA;
    public static final int ICON_5G_UWB;
    public static final int ICON_CWF;
    public static final int ICON_E;
    public static final int ICON_G;
    public static final int ICON_H;
    public static final int ICON_H_PLUS;
    public static final int ICON_LTE;
    public static final int ICON_LTE_PLUS;
    public static final Map<String, SignalIcon.MobileIconGroup> ICON_NAME_TO_ICON;
    public static final int ICON_VOWIFI;
    public static final int ICON_VOWIFI_CALLING;
    public static final SignalIcon.MobileIconGroup LTE;
    public static final SignalIcon.MobileIconGroup LTE_CA_5G_E;
    public static final SignalIcon.MobileIconGroup LTE_PLUS;
    public static final int[] MOBILE_CALL_STRENGTH_ICONS = {C1757R.C1759drawable.ic_mobile_call_strength_0, C1757R.C1759drawable.ic_mobile_call_strength_1, C1757R.C1759drawable.ic_mobile_call_strength_2, C1757R.C1759drawable.ic_mobile_call_strength_3, C1757R.C1759drawable.ic_mobile_call_strength_4};
    public static final SignalIcon.MobileIconGroup NOT_DEFAULT_DATA;
    public static final SignalIcon.MobileIconGroup NR_5G;
    public static final SignalIcon.MobileIconGroup NR_5G_PLUS;
    public static final SignalIcon.MobileIconGroup ONE_X;
    public static final SignalIcon.MobileIconGroup THREE_G;
    public static final SignalIcon.MobileIconGroup UNKNOWN;
    public static final SignalIcon.MobileIconGroup VOWIFI;
    public static final SignalIcon.MobileIconGroup VOWIFI_CALLING;
    public static final SignalIcon.MobileIconGroup WFC;
    public static final int[] WIFI_CALL_STRENGTH_ICONS = {C1757R.C1759drawable.ic_wifi_call_strength_0, C1757R.C1759drawable.ic_wifi_call_strength_1, C1757R.C1759drawable.ic_wifi_call_strength_2, C1757R.C1759drawable.ic_wifi_call_strength_3, C1757R.C1759drawable.ic_wifi_call_strength_4};

    static {
        int i = C1757R.C1759drawable.ic_lte_mobiledata;
        ICON_LTE = i;
        int i2 = C1757R.C1759drawable.ic_lte_plus_mobiledata;
        ICON_LTE_PLUS = i2;
        int i3 = C1757R.C1759drawable.ic_g_mobiledata;
        ICON_G = i3;
        int i4 = C1757R.C1759drawable.ic_e_mobiledata;
        ICON_E = i4;
        int i5 = C1757R.C1759drawable.ic_h_mobiledata;
        ICON_H = i5;
        int i6 = C1757R.C1759drawable.ic_h_plus_mobiledata;
        ICON_H_PLUS = i6;
        int i7 = C1757R.C1759drawable.ic_3g_mobiledata;
        ICON_3G = i7;
        int i8 = C1757R.C1759drawable.ic_4g_mobiledata;
        ICON_4G = i8;
        int i9 = C1757R.C1759drawable.ic_4g_plus_mobiledata;
        ICON_4G_PLUS = i9;
        int i10 = C1757R.C1759drawable.ic_4g_lte_mobiledata;
        ICON_4G_LTE = i10;
        int i11 = C1757R.C1759drawable.ic_4g_lte_plus_mobiledata;
        ICON_4G_LTE_PLUS = i11;
        int i12 = C1757R.C1759drawable.ic_5g_e_mobiledata;
        ICON_5G_E = i12;
        int i13 = C1757R.C1759drawable.ic_1x_mobiledata;
        ICON_1X = i13;
        int i14 = C1757R.C1759drawable.ic_5g_mobiledata;
        ICON_5G = i14;
        int i15 = C1757R.C1759drawable.ic_5g_plus_mobiledata;
        ICON_5G_PLUS = i15;
        int i16 = C1757R.C1759drawable.ic_carrier_wifi;
        ICON_CWF = i16;
        int i17 = C1757R.C1759drawable.ic_5g_mobiledata;
        ICON_5G_SA = i17;
        int i18 = C1757R.C1759drawable.ic_5g_mobiledata;
        ICON_5G_BASIC = i18;
        int i19 = C1757R.C1759drawable.ic_5g_uwb_mobiledata;
        ICON_5G_UWB = i19;
        int i20 = C1757R.C1759drawable.ic_vowifi;
        ICON_VOWIFI = i20;
        int i21 = C1757R.C1759drawable.ic_vowifi_calling;
        ICON_VOWIFI_CALLING = i21;
        SignalIcon.MobileIconGroup mobileIconGroup = new SignalIcon.MobileIconGroup("CARRIER_NETWORK_CHANGE", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.carrier_network_change_mode, 0);
        CARRIER_NETWORK_CHANGE = mobileIconGroup;
        SignalIcon.MobileIconGroup mobileIconGroup2 = new SignalIcon.MobileIconGroup("3G", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_3g, i7);
        THREE_G = mobileIconGroup2;
        SignalIcon.MobileIconGroup mobileIconGroup3 = new SignalIcon.MobileIconGroup("WFC", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], 0, 0);
        WFC = mobileIconGroup3;
        SignalIcon.MobileIconGroup mobileIconGroup4 = new SignalIcon.MobileIconGroup(FooterBarMixinMetrics.FooterButtonVisibility.UNKNOWN, (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], 0, 0);
        UNKNOWN = mobileIconGroup4;
        SignalIcon.MobileIconGroup mobileIconGroup5 = new SignalIcon.MobileIconGroup("E", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_edge, i4);
        f249E = mobileIconGroup5;
        SignalIcon.MobileIconGroup mobileIconGroup6 = new SignalIcon.MobileIconGroup("1X", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_cdma, i13);
        ONE_X = mobileIconGroup6;
        SignalIcon.MobileIconGroup mobileIconGroup7 = mobileIconGroup3;
        SignalIcon.MobileIconGroup mobileIconGroup8 = mobileIconGroup;
        SignalIcon.MobileIconGroup mobileIconGroup9 = new SignalIcon.MobileIconGroup("G", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_gprs, i3);
        f250G = mobileIconGroup9;
        SignalIcon.MobileIconGroup mobileIconGroup10 = new SignalIcon.MobileIconGroup(DateFormat.HOUR24, (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_3_5g, i5);
        f251H = mobileIconGroup10;
        SignalIcon.MobileIconGroup mobileIconGroup11 = new SignalIcon.MobileIconGroup("H+", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_3_5g_plus, i6);
        H_PLUS = mobileIconGroup11;
        SignalIcon.MobileIconGroup mobileIconGroup12 = new SignalIcon.MobileIconGroup("4G", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_4g, i8);
        FOUR_G = mobileIconGroup12;
        SignalIcon.MobileIconGroup mobileIconGroup13 = new SignalIcon.MobileIconGroup("4G+", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_4g_plus, i9);
        FOUR_G_PLUS = mobileIconGroup13;
        SignalIcon.MobileIconGroup mobileIconGroup14 = r1;
        SignalIcon.MobileIconGroup mobileIconGroup15 = new SignalIcon.MobileIconGroup("LTE", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_lte, i);
        LTE = mobileIconGroup14;
        SignalIcon.MobileIconGroup mobileIconGroup16 = r0;
        SignalIcon.MobileIconGroup mobileIconGroup17 = new SignalIcon.MobileIconGroup("LTE+", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_lte_plus, i2);
        LTE_PLUS = mobileIconGroup16;
        SignalIcon.MobileIconGroup mobileIconGroup18 = new SignalIcon.MobileIconGroup("4G LTE", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_4g_lte, i10);
        FOUR_G_LTE = mobileIconGroup18;
        SignalIcon.MobileIconGroup mobileIconGroup19 = new SignalIcon.MobileIconGroup("4G LTE+", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_4g_lte_plus, i11);
        FOUR_G_LTE_PLUS = mobileIconGroup19;
        SignalIcon.MobileIconGroup mobileIconGroup20 = new SignalIcon.MobileIconGroup("5Ge", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_5ge_html, i12);
        LTE_CA_5G_E = mobileIconGroup20;
        SignalIcon.MobileIconGroup mobileIconGroup21 = new SignalIcon.MobileIconGroup("5G", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_5g, i14);
        NR_5G = mobileIconGroup21;
        SignalIcon.MobileIconGroup mobileIconGroup22 = new SignalIcon.MobileIconGroup("5G_PLUS", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_5g_plus, i15);
        NR_5G_PLUS = mobileIconGroup22;
        SignalIcon.MobileIconGroup mobileIconGroup23 = new SignalIcon.MobileIconGroup("DataDisabled", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.cell_data_off_content_description, 0);
        DATA_DISABLED = mobileIconGroup23;
        SignalIcon.MobileIconGroup mobileIconGroup24 = new SignalIcon.MobileIconGroup("NotDefaultData", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.not_default_data_content_description, 0);
        NOT_DEFAULT_DATA = mobileIconGroup24;
        CARRIER_MERGED_WIFI = new SignalIcon.MobileIconGroup("CWF", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_carrier_wifi, i16);
        FIVE_G = new SignalIcon.MobileIconGroup("5G", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_5g, i14);
        FIVE_G_BASIC = new SignalIcon.MobileIconGroup("5GBasic", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_5g_basic, i18);
        SignalIcon.MobileIconGroup mobileIconGroup25 = new SignalIcon.MobileIconGroup("5GUWB", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_5g_uwb, i19);
        FIVE_G_UWB = mobileIconGroup25;
        FIVE_G_SA = new SignalIcon.MobileIconGroup("5GSA", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], C1757R.string.data_connection_5g_sa, i17);
        VOWIFI = new SignalIcon.MobileIconGroup("VoWIFI", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], 0, i20);
        VOWIFI_CALLING = new SignalIcon.MobileIconGroup("VoWIFICall", (int[][]) null, (int[][]) null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, 0, 0, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], 0, i21);
        HashMap hashMap = new HashMap();
        ICON_NAME_TO_ICON = hashMap;
        hashMap.put("carrier_network_change", mobileIconGroup8);
        hashMap.put("3g", mobileIconGroup2);
        hashMap.put("wfc", mobileIconGroup7);
        hashMap.put(EnvironmentCompat.MEDIA_UNKNOWN, mobileIconGroup4);
        hashMap.put("e", mobileIconGroup5);
        hashMap.put("1x", mobileIconGroup6);
        hashMap.put("g", mobileIconGroup9);
        hashMap.put("h", mobileIconGroup10);
        hashMap.put("h+", mobileIconGroup11);
        hashMap.put("4g", mobileIconGroup12);
        hashMap.put("4g+", mobileIconGroup13);
        hashMap.put("4glte", mobileIconGroup18);
        hashMap.put("4glte+", mobileIconGroup19);
        hashMap.put("5ge", mobileIconGroup20);
        hashMap.put("lte", mobileIconGroup14);
        hashMap.put("lte+", mobileIconGroup16);
        hashMap.put("5g", mobileIconGroup21);
        hashMap.put("5g_plus", mobileIconGroup22);
        hashMap.put("5guwb", mobileIconGroup25);
        hashMap.put("datadisable", mobileIconGroup23);
        hashMap.put("notdefaultdata", mobileIconGroup24);
    }
}
