package com.android.settingslib.mobile;

import com.android.settingslib.AccessibilityContentDescriptions;
import com.android.settingslib.R$drawable;
import com.android.settingslib.R$string;
import com.android.settingslib.SignalIcon$MobileIconGroup;
import java.util.HashMap;
import java.util.Map;

public class TelephonyIcons {
    public static final SignalIcon$MobileIconGroup CARRIER_MERGED_WIFI;
    public static final SignalIcon$MobileIconGroup CARRIER_NETWORK_CHANGE;
    public static final SignalIcon$MobileIconGroup DATA_DISABLED;

    /* renamed from: E */
    public static final SignalIcon$MobileIconGroup f232E;
    public static final SignalIcon$MobileIconGroup FIVE_G;
    public static final SignalIcon$MobileIconGroup FIVE_G_BASIC;
    public static final SignalIcon$MobileIconGroup FIVE_G_SA;
    public static final SignalIcon$MobileIconGroup FIVE_G_UWB;
    public static final int FLIGHT_MODE_ICON = R$drawable.stat_sys_airplane_mode;
    public static final SignalIcon$MobileIconGroup FOUR_G;
    public static final SignalIcon$MobileIconGroup FOUR_G_LTE;
    public static final SignalIcon$MobileIconGroup FOUR_G_LTE_PLUS;
    public static final SignalIcon$MobileIconGroup FOUR_G_PLUS;

    /* renamed from: G */
    public static final SignalIcon$MobileIconGroup f233G;

    /* renamed from: H */
    public static final SignalIcon$MobileIconGroup f234H;
    public static final SignalIcon$MobileIconGroup H_PLUS;
    public static final int ICON_1X;
    public static final int ICON_3G;
    public static final int ICON_4G;
    public static final int ICON_4G_LTE;
    public static final int ICON_4G_LTE_PLUS;
    public static final int ICON_4G_PLUS;
    public static final int ICON_5G;
    public static final int ICON_5G_BASIC;
    public static final int ICON_5G_E;
    public static final int ICON_5G_PLUS;
    public static final int ICON_5G_SA;
    public static final int ICON_5G_UWB;
    public static final int ICON_CWF;
    public static final int ICON_E;
    public static final int ICON_G;
    public static final int ICON_H;
    public static final int ICON_H_PLUS;
    public static final int ICON_LTE;
    public static final int ICON_LTE_PLUS;
    public static final Map<String, SignalIcon$MobileIconGroup> ICON_NAME_TO_ICON;
    public static final int ICON_VOWIFI;
    public static final int ICON_VOWIFI_CALLING;
    public static final SignalIcon$MobileIconGroup LTE;
    public static final SignalIcon$MobileIconGroup LTE_CA_5G_E;
    public static final SignalIcon$MobileIconGroup LTE_PLUS;
    public static final int[] MOBILE_CALL_STRENGTH_ICONS = {R$drawable.ic_mobile_call_strength_0, R$drawable.ic_mobile_call_strength_1, R$drawable.ic_mobile_call_strength_2, R$drawable.ic_mobile_call_strength_3, R$drawable.ic_mobile_call_strength_4};
    public static final SignalIcon$MobileIconGroup NOT_DEFAULT_DATA;
    public static final SignalIcon$MobileIconGroup NR_5G;
    public static final SignalIcon$MobileIconGroup NR_5G_PLUS;
    public static final SignalIcon$MobileIconGroup ONE_X;
    public static final SignalIcon$MobileIconGroup THREE_G;
    public static final SignalIcon$MobileIconGroup UNKNOWN;
    public static final SignalIcon$MobileIconGroup VOWIFI;
    public static final SignalIcon$MobileIconGroup VOWIFI_CALLING;
    public static final SignalIcon$MobileIconGroup WFC;
    public static final int[] WIFI_CALL_STRENGTH_ICONS = {R$drawable.ic_wifi_call_strength_0, R$drawable.ic_wifi_call_strength_1, R$drawable.ic_wifi_call_strength_2, R$drawable.ic_wifi_call_strength_3, R$drawable.ic_wifi_call_strength_4};

    static {
        int i = R$drawable.ic_lte_mobiledata;
        ICON_LTE = i;
        int i2 = R$drawable.ic_lte_plus_mobiledata;
        ICON_LTE_PLUS = i2;
        int i3 = R$drawable.ic_g_mobiledata;
        ICON_G = i3;
        int i4 = R$drawable.ic_e_mobiledata;
        ICON_E = i4;
        int i5 = R$drawable.ic_h_mobiledata;
        ICON_H = i5;
        int i6 = R$drawable.ic_h_plus_mobiledata;
        ICON_H_PLUS = i6;
        int i7 = R$drawable.ic_3g_mobiledata;
        ICON_3G = i7;
        int i8 = R$drawable.ic_4g_mobiledata;
        ICON_4G = i8;
        int i9 = R$drawable.ic_4g_plus_mobiledata;
        ICON_4G_PLUS = i9;
        int i10 = R$drawable.ic_4g_lte_mobiledata;
        ICON_4G_LTE = i10;
        int i11 = R$drawable.ic_4g_lte_plus_mobiledata;
        ICON_4G_LTE_PLUS = i11;
        int i12 = R$drawable.ic_5g_e_mobiledata;
        ICON_5G_E = i12;
        int i13 = R$drawable.ic_1x_mobiledata;
        ICON_1X = i13;
        int i14 = R$drawable.ic_5g_mobiledata;
        ICON_5G = i14;
        int i15 = R$drawable.ic_5g_plus_mobiledata;
        ICON_5G_PLUS = i15;
        int i16 = R$drawable.ic_carrier_wifi;
        ICON_CWF = i16;
        ICON_5G_SA = i14;
        ICON_5G_BASIC = i14;
        int i17 = R$drawable.ic_5g_uwb_mobiledata;
        ICON_5G_UWB = i17;
        int i18 = R$drawable.ic_vowifi;
        ICON_VOWIFI = i18;
        int i19 = R$drawable.ic_vowifi_calling;
        ICON_VOWIFI_CALLING = i19;
        int[] iArr = AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH;
        int[] iArr2 = iArr;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup = new SignalIcon$MobileIconGroup("CARRIER_NETWORK_CHANGE", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], R$string.carrier_network_change_mode, 0);
        CARRIER_NETWORK_CHANGE = signalIcon$MobileIconGroup;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup2 = new SignalIcon$MobileIconGroup("3G", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_3g, i7);
        THREE_G = signalIcon$MobileIconGroup2;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup3 = new SignalIcon$MobileIconGroup("WFC", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], 0, 0);
        WFC = signalIcon$MobileIconGroup3;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup4 = new SignalIcon$MobileIconGroup("Unknown", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], 0, 0);
        UNKNOWN = signalIcon$MobileIconGroup4;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup5 = new SignalIcon$MobileIconGroup("E", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_edge, i4);
        f232E = signalIcon$MobileIconGroup5;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup6 = new SignalIcon$MobileIconGroup("1X", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_cdma, i13);
        ONE_X = signalIcon$MobileIconGroup6;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup7 = signalIcon$MobileIconGroup4;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup8 = signalIcon$MobileIconGroup3;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup9 = signalIcon$MobileIconGroup;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup10 = new SignalIcon$MobileIconGroup("G", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_gprs, i3);
        f233G = signalIcon$MobileIconGroup10;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup11 = new SignalIcon$MobileIconGroup("H", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_3_5g, i5);
        f234H = signalIcon$MobileIconGroup11;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup12 = new SignalIcon$MobileIconGroup("H+", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_3_5g_plus, i6);
        H_PLUS = signalIcon$MobileIconGroup12;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup13 = new SignalIcon$MobileIconGroup("4G", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_4g, i8);
        FOUR_G = signalIcon$MobileIconGroup13;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup14 = new SignalIcon$MobileIconGroup("4G+", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_4g_plus, i9);
        FOUR_G_PLUS = signalIcon$MobileIconGroup14;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup15 = r1;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup16 = new SignalIcon$MobileIconGroup("LTE", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_lte, i);
        LTE = signalIcon$MobileIconGroup15;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup17 = r0;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup18 = new SignalIcon$MobileIconGroup("LTE+", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_lte_plus, i2);
        LTE_PLUS = signalIcon$MobileIconGroup17;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup19 = new SignalIcon$MobileIconGroup("4G LTE", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_4g_lte, i10);
        FOUR_G_LTE = signalIcon$MobileIconGroup19;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup20 = new SignalIcon$MobileIconGroup("4G LTE+", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_4g_lte_plus, i11);
        FOUR_G_LTE_PLUS = signalIcon$MobileIconGroup20;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup21 = new SignalIcon$MobileIconGroup("5Ge", (int[][]) null, (int[][]) null, iArr, 0, 0, 0, 0, iArr[0], R$string.data_connection_5ge_html, i12);
        LTE_CA_5G_E = signalIcon$MobileIconGroup21;
        int i20 = iArr[0];
        int i21 = R$string.data_connection_5g;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup22 = new SignalIcon$MobileIconGroup("5G", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, i20, i21, i14);
        NR_5G = signalIcon$MobileIconGroup22;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup23 = new SignalIcon$MobileIconGroup("5G_PLUS", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], R$string.data_connection_5g_plus, i15);
        NR_5G_PLUS = signalIcon$MobileIconGroup23;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup24 = new SignalIcon$MobileIconGroup("DataDisabled", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], R$string.cell_data_off_content_description, 0);
        DATA_DISABLED = signalIcon$MobileIconGroup24;
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup25 = new SignalIcon$MobileIconGroup("NotDefaultData", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], R$string.not_default_data_content_description, 0);
        NOT_DEFAULT_DATA = signalIcon$MobileIconGroup25;
        CARRIER_MERGED_WIFI = new SignalIcon$MobileIconGroup("CWF", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], R$string.data_connection_carrier_wifi, i16);
        int i22 = i14;
        FIVE_G = new SignalIcon$MobileIconGroup("5G", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], i21, i22);
        FIVE_G_BASIC = new SignalIcon$MobileIconGroup("5GBasic", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], R$string.data_connection_5g_basic, i22);
        SignalIcon$MobileIconGroup signalIcon$MobileIconGroup26 = new SignalIcon$MobileIconGroup("5GUWB", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], R$string.data_connection_5g_uwb, i17);
        FIVE_G_UWB = signalIcon$MobileIconGroup26;
        FIVE_G_SA = new SignalIcon$MobileIconGroup("5GSA", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], R$string.data_connection_5g_sa, i14);
        VOWIFI = new SignalIcon$MobileIconGroup("VoWIFI", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], 0, i18);
        VOWIFI_CALLING = new SignalIcon$MobileIconGroup("VoWIFICall", (int[][]) null, (int[][]) null, iArr2, 0, 0, 0, 0, iArr[0], 0, i19);
        HashMap hashMap = new HashMap();
        ICON_NAME_TO_ICON = hashMap;
        hashMap.put("carrier_network_change", signalIcon$MobileIconGroup9);
        hashMap.put("3g", signalIcon$MobileIconGroup2);
        hashMap.put("wfc", signalIcon$MobileIconGroup8);
        hashMap.put("unknown", signalIcon$MobileIconGroup7);
        hashMap.put("e", signalIcon$MobileIconGroup5);
        hashMap.put("1x", signalIcon$MobileIconGroup6);
        hashMap.put("g", signalIcon$MobileIconGroup10);
        hashMap.put("h", signalIcon$MobileIconGroup11);
        hashMap.put("h+", signalIcon$MobileIconGroup12);
        hashMap.put("4g", signalIcon$MobileIconGroup13);
        hashMap.put("4g+", signalIcon$MobileIconGroup14);
        hashMap.put("4glte", signalIcon$MobileIconGroup19);
        hashMap.put("4glte+", signalIcon$MobileIconGroup20);
        hashMap.put("5ge", signalIcon$MobileIconGroup21);
        hashMap.put("lte", signalIcon$MobileIconGroup15);
        hashMap.put("lte+", signalIcon$MobileIconGroup17);
        hashMap.put("5g", signalIcon$MobileIconGroup22);
        hashMap.put("5g_plus", signalIcon$MobileIconGroup23);
        hashMap.put("5guwb", signalIcon$MobileIconGroup26);
        hashMap.put("datadisable", signalIcon$MobileIconGroup24);
        hashMap.put("notdefaultdata", signalIcon$MobileIconGroup25);
    }
}
