package android.provider;

import android.net.Uri;
import android.provider.Settings;
import android.util.ArraySet;
import java.util.HashSet;
import java.util.Set;
/* loaded from: classes2.dex */
public final class NtSettings {

    /* loaded from: classes2.dex */
    public static final class Global {
        public static final String ADAPTIVE_KEEP_BRIGHT_SCREEN = "adaptive_keep_bright_screen";
        public static final String ANTI_ADDICTION_MODE = "nt_anti_addiction_mode";
        public static final String AUTO_ANSWER_INCOMING_RINGING = "auto_answer_incoming_ringing";
        public static final String AUTO_RECORD_ALERT_COUNT = "auto_record_alert_count";
        public static final String AUTO_RECORD_WHEN_CALLING = "auto_record_when_calling";
        public static final String BLUE_REDUCTION_CONFIG_TYPE = "blue_reduction_config_type";
        public static final String CACHED_APPS_FREEZER_ENABLED_FAST = "cached_apps_freezer_fast";
        public static final String CACHED_APPS_IDLE_FREEZER_ENABLED = "cached_apps_idle_freezer";
        public static final String CHARGED_SOUND = "charged_sound";
        public static final String CHIILDREN_APPS_LIST = "child_app_list";
        public static final String CHILDREN_ANTI_ADDICTION_TIME = "child_anti_addiction_time";
        public static final String CHILDREN_LAUNCHER_ICON = "children_launcher_icon";
        public static final String CHILDREN_LOW_POWER = "child_low_power";
        public static final String CHILDREN_MOBILE_DATA = "children_mobile_data";
        public static final String CHILDREN_MOBILE_DATA_BACKUP = "children_mobile_data_backup";
        public static final String CHILDREN_MODE = "children_mode";
        public static final String CHILDREN_MODE_RUNNING_TIME = "child_mode_running_time";
        public static final String CHILDREN_SMS_ANTI_COST = "children_sms_anti_cost";
        public static final String CURRENT_SCREEN_COLOR_TEMPERATURE = "current_screen_color_temperature";
        public static final String DEVELOPER_OPTION = "nt_developer_option";
        public static final String DISPLAY_DEVELOPER_MODE_NOTIFICATION = "display_developer_mode_notification";
        public static final String DISPLAY_SOURCE_COLOR_ENABLE = "nt_display_source_Color_enable";
        public static final String DUAL_WIFI_ENABLED_SAVED_STATE = "dual_wifi_saved_state";
        public static final String DUAL_WIFI_ENABLED_STATE = "dual_wifi_enabled";
        public static final String FINGERPRINT_ANIMATION = "fingerprint_animation";
        public static final String FINGERPRINT_AUTHENTICATING_IN_AOD = "fp_authenticate_in_aod_mode";
        public static final String HAPTIC_FEEDBACK_GLOBAL_KEYBOARD_STRENGTH = "haptic_feedback_global_keyboard_strength";
        public static final String HAPTIC_FEEDBACK_GLOBAL_UI_STRENGTH = "haptic_feedback_global_ui_strength";
        public static final String HAPTIC_FEEDBACK_INITIALIZED = "haptic_feedback_initialized";
        public static final String HAPTIC_FEEDBACK_KEYBOARD_DEVICE_HANDLE = "haptic_feedback_keyboard_devicehandle";
        public static final String HAPTIC_FEEDBACK_NOTIFICATION_UI_DEVICE_HANDLE = "haptic_feedback_ui_notification_devicehandle";
        public static final String HAPTIC_FEEDBACK_UI_DEVICE_HANDLE = "haptic_feedback_ui_devicehandle";
        public static final String HOME_SLIDE_DTU = "home_slide_dtu";
        public static final String HOME_SLIDE_LTR = "home_slide_ltr";
        public static final String HOME_SLIDE_RTL = "home_slide_rtl";
        public static final String IMMEDIATELY_ON_OR_OFF = "immediately_on_or_off";
        public static final String INCOMING_FLASH_REMINDER = "incoming_flash_reminder";
        public static final String INTERCEPT_POERKEY_BY_APPLICATION = "intercpt_powerkey";
        public static final String LED_BED_TIME_CUSTOM_END_TIME = "led_bed_time_custom_end_time";
        public static final String LED_BED_TIME_CUSTOM_START_TIME = "led_bed_time_custom_start_time";
        public static final String LED_BED_TIME_CUSTOM_WEEK = "led_bed_time_custom_week";
        public static final String LED_BRIGHTNESS_VALUE = "led_brightness_value";
        public static final String LED_DEFAULT_RINGTONE_SOUND_MODE = "led_default_ringtone_sound_mode";
        public static final String LED_EFFECT_BRIGHTNESS = "led_effect_brightness";
        public static final String LED_EFFECT_CALL_ENABLED = "led_effect_call_enalbe";
        public static final String LED_EFFECT_CAMERA_ENABLED = "led_effect_call_enalbe";
        public static final String LED_EFFECT_CHARGING_ENABLED = "led_effect_charging_enable";
        public static final String LED_EFFECT_ENABLED = "led_effect_enable";
        public static final String LED_EFFECT_GA_ENABLED = "led_effect_google_assistant_enalbe";
        public static final String LED_EFFECT_GESTURES_FLIP = "led_effect_gestures_flip_ebable";
        public static final String LED_EFFECT_MUSIC_ENABLED = "led_effect_music_enalbe";
        public static final String LED_EFFECT_NOTIFICATION_ENABLED = "led_effect_notification_enable";
        public static final String LED_EFFECT_SCHEDULE_TIME = "led_effect_schedule_time_ebable";
        public static final String LED_EFFECT_TALK_REACTIVE_ENABLED = "led_effect_talk_reactive_ebable";
        public static final String LED_EFFECT_VIDEO_ENABLED = "led_effect_video_enalbe";
        public static final String LED_EFFECT_WLR_CHARGING_ENABLED = "led_effect_wlr_charging_enable";
        public static final String LED_GLYPHS_SHOW_MUSIC_SWITCH = "led_glyphs_show_music_switch";
        public static final String LED_IN_BED_TIME = "led_in_bed_time";
        public static final String LED_NOTIFICATION_MODE = "led_notification_mode";
        public static final String MUTE_TENCENT_IN_DND = "nt_mute_tencent_in_dnd";
        public static final String NT_ALI_ENABLE_TRANSFER = "ali_enable_transfer";
        public static final String NT_AUDIO_PERMISSION = "nt_audio_permission";
        public static final String NT_BATTERY_HEALTH = "nt_battery_health";
        public static final String NT_BLUETOOTH_CONNECT_AFTER_PAIR = "bluetooth_connect_after_pair";
        public static final String NT_BLUETOOTH_HOST_START_PAIR = "bluetooth_host_start_pair";
        public static final String NT_CAMERA_PERMISSION = "nt_camera_permission";
        public static final String NT_CN_GMS_CORE = "cn_gms_core";
        public static final String NT_CONTACTS_PERMISSION = "nt_contacts_permission";
        public static final String NT_DEFAULT_ALARM_VIBRATOR_TIMEOUT = "nt_default_alarm_timeout";
        public static final String NT_DEFAULT_RINGTONE_VIBRATOR_TIMEOUT = "nt_default_ringtone_timeout";
        public static final String NT_FAST_CHARGE = "nt_fast_charge";
        public static final String NT_FREE_WIFI_DISABLED_REASON = "free_wifi_disabled_reason";
        public static final String NT_FREE_WIFI_ENABLER = "free_wifi_enabler";
        public static final String NT_FREE_WIFI_NOTIFY = "free_wifi_notify";
        public static final String NT_FRINGE_HIDE = "nt_fringe_hide";
        public static final String NT_HIGH_CONTRAST_MODE = "NT_high_contrast_mode";
        public static final String NT_INFO_PHONE_NUMBER_ENABLE = "enable_query_info_phone_number";
        public static final String NT_LAKALA_ENABLE_TRANSFER = "lakala_enable_transfer";
        public static final String NT_LOCATION_PERMISSION = "nt_location_permission";
        public static final String NT_NFC_SLEEP_MODE_WAKEUP_SCREEN = "nfc_sleep_mode_wakeup_screen";
        public static final String NT_REVERSE_CHARGING_LIMITING_LEVEL = "nt_reverse_charging_limiting_level";
        public static final String NT_SCREEN_COLOR_TEMPERATURE = "current_screen_color_temperature";
        public static final String NT_SHOW_HIDDEN_MENU = "show_hidden_menu";
        public static final String NT_SHOW_NFC_STATUSBAR_SWITCH = "show_nfc_statusbar_switch";
        public static final String NT_SHOW_VPN_STATUSBAR_SWITCH = "show_vpn_statusbar_switch";
        public static final String NT_TETHER_ENABLE_BLUETOOTH = "tether_enable_bluetooth";
        public static final String NT_USER_ON_BT_AIRPLANE = "nt_user_on_bt_airplane";
        public static final String NT_VIBRATOR_ALARM_RINGTONE_EFFECTID = "NT_alarm_ringid";
        public static final String NT_VIBRATOR_TELE_RINGTONE_EFFECTID = "NT_phone_ringid";
        public static final String NT_WIFI_ENABLE_SLEEP_AT_NIGHT = "wifi_enable_sleep_at_night";
        public static final String NT_WIFI_SCAN_ALWAYS_AVAILABLE_REMEMBERED = "wifi_scan_always_enabled_remembered";
        public static final String NT_WIRELESS_REVERSE_CHARGE = "nt_wireless_reverse_charge";
        public static final String PLUDIN_SOUND = "plugin_sound";
        public static final String PREFIX_DIALING_NUMBER = "prefix_dialing_number";
        public static final String PRIVATE_ASSOCIATE_NT_ACCOUNT = "nt_private_associate_NT_account";
        public static final String PRIVATE_BROWSER_MODE_ENABLE = "nt_private_browser_mode";
        public static final String PRIVATE_CAMERA_MODE_ENABLE = "nt_private_camera_mode";
        public static final String PRIVATE_MODE_ENABLE = "nt_private_mode";
        public static final String PRIVATE_MODE_RUNNING = "nt_private_mode_running";
        public static final String PRIVATE_MODE_SWTICH_REASON = "private_mode_switch_reason";
        public static final String PRIVATE_PACKAGES_LIST = "private_pkg_list";
        public static final String RECENTS_LAYOUT_DIRECTION = "recents_layout_direction";
        public static final String SCREEN_REFRESH_RATE = "screen_refresh_rate";
        public static final String SELF_CONFIG_TIME_END_HOUR = "self_config_time_end_hour";
        public static final String SELF_CONFIG_TIME_END_MINUTE = "self_config_time_end_minute";
        public static final String SELF_CONFIG_TIME_START_HOUR = "self_config_time_start_hour";
        public static final String SELF_CONFIG_TIME_START_MINUTE = "self_config_time_start_minute";
        public static final String SMART_NETWORK_SWITCH = "smart_network_switch";
        public static final String SOS_MODE = "NT_sos_mode";
        public static final String SOS_MODE_NEED_RESTORE_FACE_RECOGNITION = "NT_sos_mode_need_restore_face";
        public static final String SOS_MODE_NEED_RESTORE_FINGERPRINT = "NT_sos_mode_need_restore_fp";
        public static final String SUNRISE_TIME = "sunrise_time";
        public static final String SUNSET_TIME = "sunset_time";
        public static final String TIME_CONFIG_TYPE = "time_config_type";
        public static final String VIBRATE_WHEN_MOCALL_CONNECTED = "vibrate_when_mocall_connected";
        public static final String WHITE_LIST_DISTURB_ENABLE = "white_list_disturb_enable";
    }

    /* loaded from: classes2.dex */
    public static final class System {
        public static final String ALARM_ALERT_SET_FLAG = "alarm_alert_set";
        public static final String ALARM_SOUND_FILE_PATH = "alarm_sound_file_path";
        public static final String BOTTOM_BUTTON_STYLE_OTHER_APP = "bottom_button_style_other_app";
        public static final String BOTTOM_BUTTON_STYLE_PHONE = "bottom_button_style_phone";
        public static final String BUTTON_BRIGHTNESS = "button_brightness";
        public static final String CALENDAR_SOUND = "calendar_sound";
        public static final String CALENDAR_SOUND_FILE_PATH = "calendar_sound_file_path";
        public static final String CALENDAR_SOUND_SET_FLAG = "calendar_sound_set";
        public static final String CAMERA_SOUND = "camera_sound";
        public static final String CAMERA_SOUNDS_ENABLED = "camera_sounds_enabled";
        public static final String CHOOSE_NETWORK_PROVIDER_MODE = "choose_network_provider_mode";
        public static final String CLASSIC_MODE = "classic_mode";
        public static final String CLASSIC_MODE_BROWSER = "classic_mode_browser";
        public static final String CLASSIC_MODE_CALENDAR = "classic_mode_calendar";
        public static final String CLASSIC_MODE_CLOCK = "classic_mode_clock";
        public static final String CLASSIC_MODE_EMAIL = "classic_mode_email";
        public static final String CLASSIC_MODE_LAUNCHER_ICON = "classic_mode_launcher_icon";
        public static final String CLASSIC_MODE_MEMOS = "classic_mode_memos";
        public static final String CLASSIC_MODE_PAINTER = "classic_mode_painter";
        public static final String CLASSIC_MODE_SMS = "classic_mode_sms";
        public static final String CPU_L = "cpu_l";
        public static final String CURRENT_CHANGING_PACKAGE_NOTI_VISIBILITY = "pkg_noti_visibility";
        public static final String CURRENT_NOTIFICATION_FILTER_VALUE = "current_notification_filter_value";
        public static final String DESKTOP_APP_RECOMMEND = "desktop_app_recommend";
        public static final String DEV_FORCE_SHOW_NAVBAR = "dev_force_show_navbar";
        public static final String EMAIL_SOUND = "email_sound";
        public static final String EMAIL_SOUND_FILE_PATH = "email_sound_file_path";
        public static final String EMAIL_SOUND_SET_FLAG = "email_sound_set";
        public static final String ENABLE_SIP_CALL = "enable_sip_call";
        public static final String ENABLE_SIP_FEATURE = "enable_sip_feature";
        public static final String FLIPWAKEUP_SWITCH = "flipwakeup_switch";
        public static final String HALL_SWITCH = "hall_switch";
        public static final String HAPTIC_FEEDBACK_KEYBOARD_ENABLE = "haptic_feedback_keyboard_enable";
        public static final String HAPTIC_FEEDBACK_KEYBOARD_STRENGTH = "haptic_feedback_keyboard_strength";
        public static final String HAPTIC_FEEDBACK_THEME = "haptic_feedback_theme";
        public static final String HAPTIC_FEEDBACK_UI_STRENGTH = "haptic_feedback_ui_strength";
        public static final String HEADSET_MIDDLE_KEY_WAKEUP = "headset_middle_key_wakeup";
        public static final String HIFI_MUSIC = "hifi_music";
        public static final String HIFI_MUSIC_ENABLED = "hifi_music_enabled";
        public static final String HIFI_MUSIC_PARAM = "hifi_music_param";
        public static final String HOMEKEY_FEEDBACK_INTENSITY = "homekey_feedback_intensity";
        public static final String HOMEKEY_VOLUME_LEVEL = "homekey_volume_level";
        public static final String HOME_DOUBLE_CLICK = "home_double_click";
        public static final String INTERNET_CALL_SIP_ENABLE = "internet_call_switch";
        public static final String KEYBOARD_EXIT_DIRECTLY = "keyboard_exit_directly";
        public static final String KEY_SECOND_SCREEN_CARD_REMIND = "second_screen_card_remind";
        public static final String KEY_SECOND_SCREEN_CARD_REMIND_CALENDAR = "second_screen_card_remind_calendar";
        public static final String KEY_SECOND_SCREEN_CARD_REMIND_CAMERA = "second_screen_card_remind_camera";
        public static final String KEY_SECOND_SCREEN_CARD_REMIND_CLOCK = "second_screen_card_remind_clock";
        public static final String KEY_SECOND_SCREEN_CARD_REMIND_COUNT_DOWN = "second_screen_card_remind_count_down";
        public static final String KEY_SECOND_SCREEN_CARD_REMIND_INCOMING_CALL = "second_screen_card_remind_incoming_call";
        public static final String KEY_SECOND_SCREEN_CARD_REMIND_WEATHER = "second_screen_card_remind_weather";
        public static final String KEY_SECOND_SCREEN_NOTIFICATION = "second_screen_notification";
        public static final String KEY_SECOND_SCREEN_NOTIFICATION_PREFIX = "second_screen_notify_";
        public static final String KEY_SECOND_SCREEN_SCREENOFF_AIRMODE = "second_screen_screenoff_airmode";
        public static final String KEY_SECOND_SCREEN_SCREENOFF_ANIM = "second_screen_screenoff_anim";
        public static final String KEY_SECOND_SCREEN_SCREENOFF_CHARGING = "second_screen_screenoff_charging";
        public static final String KEY_SECOND_SCREEN_SCREENOFF_DND = "second_screen_screenoff_dnd";
        public static final String KEY_SECOND_SCREEN_SCREENOFF_INPUT_TEXT = "second_screen_screenoff_input_text";
        public static final String KEY_SECOND_SCREEN_SCREENOFF_MUSIC = "second_screen_screenoff_music";
        public static final String KEY_SECOND_SCREEN_SCREENOFF_PHONE_CALLING = "second_screen_screenoff_calling";
        public static final String KEY_SECOND_SCREEN_SCREENOFF_VOICE_ASSIS = "second_screen_screenoff_voice_assis";
        public static final String KEY_SECOND_SCREEN_SCREENOFF_WIRELESS = "second_screen_screenoff_wireless";
        public static final String KEY_SECOND_SCREEN_SWITCH = "second_screen_switch";
        public static final String KEY_SOUND = "key_sound";
        public static final String KEY_SOUNDS_ENABLED = "key_sounds_enabled";
        public static final String KEY_SYSTEM_TIPS_SOUND = "key_system_tips_sound";
        public static final String LIGHT_FEEDBACK_ENABLED = "light_feedback_enabled";
        public static final String LIST_HOLD_SOUND = "list_hold_sound";
        public static final String LOCKSCREEN_PULL_NOTIFICATIONBAR = "lockscreen_pull_notificationbar";
        public static final String LOCKSCREEN_SHOW_LUNAR_CALENDER = "lockscreen_lunar_calender";
        public static final String LOCKSCREEN_SHOW_MUSIC = "lockscreen_music";
        public static final String MMS_SOUND = "mms_sound";
        public static final String MMS_SOUND_FILE_PATH = "mms_sound_file_path";
        public static final String MMS_SOUND_SET_FLAG = "mms_sound_set";
        public static final String MODE_RING_UP = "mode_ring_up";
        public static final String MSIM_MODE_SETTING = "msim_mode_setting";
        public static final String NETWORK_PROVIDER_PACKAGE = "network_provider_package";
        public static final String NOTIFICATION_INTERCEPTION_AUTO_CLEAR = "NT_notification_interception_auto_clear";
        public static final String NOTIFICATION_INTERCEPTION_SHOW_NUMBER = "NT_notification_interception_show_number";
        public static final String NOTIFICATION_SHOW_LIGHTS = "notification_show_lights";
        public static final String NOTIFICATION_SOUND_FILE_PATH = "notification_sound_file_path";
        public static final String NOTIFICATION_SOUND_SET_FLAG = "notification_sound_set";
        public static final String NOTIFICATION_WAKEUP_SCREEN = "notification_wakeup_screen";
        public static final String NT_APP_LOCK_CONTROL = "nt_app_lock_control";
        public static final String NT_ASSISTANT_APP_OPEN_STATE = "nt_assistant_app_open_state";
        public static final String NT_BUBBLE_NOTIFICATION = "nt_bubble_notification";
        public static final String NT_CURRENT_NAVIGATION_MODE = "nt_current_navigation_mode";
        public static final String NT_CURRENT_NETWROK_SPEED = "nt_current_network_speed";
        public static final String NT_DATA_COLLECTION = "nt_data_collection";
        public static final String NT_DATA_SERVICE_RUNNING = "nt_data_service_running";
        public static final String NT_DISPLAY_LUT_MODE = "nt_display_lut_mode";
        public static final String NT_DOCUMENT_LOCK = "nt_document_lock";
        public static final String NT_DO_NOT_DISTURB_ALLOW_EXIT_DIALOG_FLAG = "nt_do_not_disturb_allow_exit_dialog_flag";
        public static final String NT_DO_NOT_DISTURB_END_TIME = "nt_do_not_disturb_end_time";
        public static final String NT_DO_NOT_DISTURB_END_TIME_HOUR = "nt_do_not_disturb_end_time_hour";
        public static final String NT_DO_NOT_DISTURB_END_TIME_MINUTE = "nt_do_not_disturb_end_time_minutes";
        public static final String NT_DO_NOT_DISTURB_HEADS_UP_NOTIFICATION = "nt_do_not_disturb_heads_up_notification";
        public static final String NT_DO_NOT_DISTURB_INTERRUPTION_FILTER = "nt_do_not_disturb_interruption_filter";
        public static final String NT_DO_NOT_DISTURB_IS_WORKING = "nt_do_not_disturb_is_working";
        public static final String NT_DO_NOT_DISTURB_PRE_PULSE_STATE = "nt_do_not_disturb_pre_pulse_state";
        public static final String NT_DO_NOT_DISTURB_PRE_RINGER_MODE = "nt_do_not_disturb_pre_ringer_mode";
        public static final String NT_DO_NOT_DISTURB_PRE_VIBRATE_STATE = "nt_do_not_disturb_pre_vibrate_state";
        public static final String NT_DO_NOT_DISTURB_PRIORITY_APPS = "nt_do_not_disturb_priority_apps";
        public static final String NT_DO_NOT_DISTURB_REMIND_REPEATING_COMING_CALL = "nt_do_not_disturb_remind_repeating_coming _call";
        public static final String NT_DO_NOT_DISTURB_REPEAT_DAYS = "nt_do_not_disturb_repeat_days";
        public static final String NT_DO_NOT_DISTURB_RULE_BACKUP = "nt_do_not_disturb_rule_backup";
        public static final String NT_DO_NOT_DISTURB_SCREEN_NOT_WAKEUP_BY_NOTIFICATION = "nt_do_not_disturb_screen_not_wakeup_by_notification";
        public static final String NT_DO_NOT_DISTURB_SCREEN_OFF_TIME = "nt_do_not_disturb_screen_off_time";
        public static final String NT_DO_NOT_DISTURB_START_TIME = "nt_do_not_disturb_start_time";
        public static final String NT_DO_NOT_DISTURB_START_TIME_HOUR = "nt_do_not_disturb_start_time_hour";
        public static final String NT_DO_NOT_DISTURB_START_TIME_MINUTE = "nt_do_not_disturb_start_time_minute";
        public static final String NT_DO_NOT_DISTURB_TIME_SWITCH = "nt_do_not_disturb_time_switch";
        public static final String NT_DO_NOT_DISTURB_WAKEUP_BREATH_LIGHT = "nt_do_not_disturb_wakeup_breath_light";
        public static final String NT_EARPHONE_FEEDBACK_ENABLED = "earphone_feedback";
        public static final String NT_EASY_MODE = "nt_easy_mode";
        public static final String NT_ENABLE_ALARM_ALIGN = "nt_enable_alarm_align";
        public static final String NT_ENABLE_FULL_SCREEN_DRAG = "enable_full_screen_drag";
        public static final String NT_FIND_PHONE = "com.nothing.FindPhone";
        public static final String NT_FIND_PHONE_AUTO_SEND_NUMBER = "com.nothing.auto_send_number";
        public static final String NT_FIND_PHONE_LOCK_TYPE = "com.nothing.service.find.LockType";
        public static final String NT_FIND_PHONE_WIPE_ALL_NOT_VALIDATED = "nt_wipe_all_not_validated";
        public static final String NT_FLASHLAMP_EFFECTS_ALARM = "flashlamp_effects_alarm";
        public static final String NT_FLASHLAMP_EFFECTS_INCOMMING_CALL = "flashlamp_effects_incomming_call";
        public static final String NT_FLASHLAMP_EFFECTS_RECEIVE_SMS = "flashlamp_effects_receive_sms";
        public static final String NT_FLASHLAMP_EFFECTS_RED_ENVELOPE = "flashlamp_effects_red_envelope";
        public static final String NT_FLASHLAMP_EFFECTS_SEND_SMS = "flashlamp_effects_send_sms";
        public static final String NT_FLASHLAMP_EFFECTS_SWITCH = "flashlamp_effects_switch";
        public static final String NT_FLOAT_TOUCH_ENABLE = "nt_float_touch_enable";
        public static final String NT_FORCE_QUICK_REPLY = "nt_force_quick_reply";
        public static final String NT_FP_USE_APP_UNLOCK = "nt_fingerprint_use_app_unlock";
        public static final String NT_FP_USE_DOCUMENT_UNLOCK = "nt_fingerprint_use_document_unlock";
        public static final String NT_FP_USE_PAYMENT = "nt_fingerprint_use_payment";
        public static final String NT_FP_USE_UNLOCK = "nt_fingerprint_use_unlock";
        public static final String NT_GUARD_MODE = "nt_guard_mode";
        public static final String NT_HOLSTER_HALL_MODE = "nt_holster_hall_mode";
        public static final String NT_HOME_KEY_TOUCH_BEHAVIOR = "nt_home_key_touch_behavior";
        public static final String NT_INTELLIGENT_VOICE = "nt_intelligent_voice";
        public static final String NT_INTELLIGENT_VOICE_HEADSET_WAKEUP = "nt_intelligent_voice_headset_wakeup";
        public static final String NT_INTELLIGENT_VOICE_HOME_WAKEUP = "nt_intelligent_voice_home_wakeup";
        public static final String NT_KEYGUARD_PALM_REJECTION_ENABLED = "keyguard_palm_rejection";
        public static final String NT_KEY_WAKEUP_TYPE = "nt_key_wakeup_type";
        public static final String NT_LARGE_LAUNCHER_ICON = "NT_boss_icon";
        public static final String NT_LOGOUT_CLEAR_FLAG = "NT_logout_clear_flag";
        public static final String NT_LONG_SCREENSHOT_RUNNING = "nt_long_screenshot_running";
        public static final String NT_MBACK_GESTURE = "mback_side_slip_gesture";
        public static final String NT_MBACK_LONG_PRESS_SCREEN_OFF = "mback_long_press_screen_off";
        public static final String NT_MEDIA_SCAN_ALL = "nt_media_scan_all";
        public static final String NT_MTP_UNLOCKED = "nt_mtp_unlocked";
        public static final String NT_NAVIGATION_BAR_BACKGROUND_COLOR = "nt_navigation_bar_background_color";
        public static final String NT_NAVIGATION_BAR_DARK_ICON = "nt_navigation_bar_dark_icon";
        public static final String NT_NAVIGATION_SIDE_GESTURE = "nt_navigation_side_gesture";
        public static final String NT_NAVIGATION_SIMPLE_GESTURE = "nt_navigation_simple_gesture";
        public static final String NT_POWER_BRIGHT_ALGOL = "nt_power_bright_algol";
        public static final String NT_POWER_LONG_PRESS_VOICE = "power_long_press_voice";
        public static final String NT_POWER_MODE = "nt_power_mode";
        public static final String NT_QUICK_WAKEUP_DOUBLE_CLICK = "nt_quick_wakeup_double_click";
        public static final String NT_QUICK_WAKEUP_DRAW_C = "nt_quick_wakeup_draw_c";
        public static final String NT_QUICK_WAKEUP_DRAW_C_PACKAGE_DETAIL = "nt_quick_wakeup_draw_c_package_detail";
        public static final String NT_QUICK_WAKEUP_DRAW_E = "nt_quick_wakeup_draw_e";
        public static final String NT_QUICK_WAKEUP_DRAW_E_PACKAGE_DETAIL = "nt_quick_wakeup_draw_e_package_detail";
        public static final String NT_QUICK_WAKEUP_DRAW_M = "nt_quick_wakeup_draw_m";
        public static final String NT_QUICK_WAKEUP_DRAW_M_PACKAGE_DETAIL = "nt_quick_wakeup_draw_m_package_detail";
        public static final String NT_QUICK_WAKEUP_DRAW_O = "nt_quick_wakeup_draw_o";
        public static final String NT_QUICK_WAKEUP_DRAW_O_PACKAGE_DETAIL = "nt_quick_wakeup_draw_o_package_detail";
        public static final String NT_QUICK_WAKEUP_DRAW_S = "nt_quick_wakeup_draw_s";
        public static final String NT_QUICK_WAKEUP_DRAW_S_PACKAGE_DETAIL = "nt_quick_wakeup_draw_s_package_detail";
        public static final String NT_QUICK_WAKEUP_DRAW_V = "nt_quick_wakeup_draw_v";
        public static final String NT_QUICK_WAKEUP_DRAW_V_PACKAGE_DETAIL = "nt_quick_wakeup_draw_v_package_detail";
        public static final String NT_QUICK_WAKEUP_DRAW_W = "nt_quick_wakeup_draw_w";
        public static final String NT_QUICK_WAKEUP_DRAW_W_PACKAGE_DETAIL = "nt_quick_wakeup_draw_w_package_detail";
        public static final String NT_QUICK_WAKEUP_DRAW_Z = "nt_quick_wakeup_draw_z";
        public static final String NT_QUICK_WAKEUP_DRAW_Z_PACKAGE_DETAIL = "nt_quick_wakeup_draw_z_package_detail";
        public static final String NT_QUICK_WAKEUP_FINGER_GESTURE = "nt_quick_wakeup_finger_gesture";
        public static final String NT_QUICK_WAKEUP_SLIDE_DOWN = "nt_quick_wakeup_slide_down";
        public static final String NT_QUICK_WAKEUP_SLIDE_LEFT = "nt_quick_wakeup_slide_left";
        public static final String NT_QUICK_WAKEUP_SLIDE_LEFT_RIGHT = "nt_quick_wakeup_slide_left_right";
        public static final String NT_QUICK_WAKEUP_SLIDE_RIGHT = "nt_quick_wakeup_slide_right";
        public static final String NT_QUICK_WAKEUP_SLIDE_RIGHT_PACKAGE_DETAIL = "nt_quick_wakeup_slide_right_package_detail";
        public static final String NT_QUICK_WAKEUP_SLIDE_UP = "nt_quick_wakeup_slide_up";
        public static final String NT_QUICK_WAKEUP_SWITCH = "nt_quick_wakeup_switch";
        public static final String NT_REGION = "nt_region";
        public static final String NT_RTNDS_ENABLE = "nt_rtnds_enable_switch";
        public static final String NT_SAFE_PAY_SHOW = "nt_safe_pay_show";
        public static final String NT_SAFE_PAY_SWITCH = "nt_safe_pay_switch";
        public static final String NT_SCHEDULED_POWER_OFF = "nt_scheduled_power_off";
        public static final String NT_SCHEDULED_POWER_OFF_DAYS = "nt_scheduled_power_off_days";
        public static final String NT_SCHEDULED_POWER_OFF_H = "nt_scheduled_power_off_h";
        public static final String NT_SCHEDULED_POWER_OFF_M = "nt_scheduled_power_off_m";
        public static final String NT_SCHEDULED_POWER_OFF_TIME = "nt_scheduled_power_off_time";
        public static final String NT_SCHEDULED_POWER_ON = "nt_scheduled_power_on";
        public static final String NT_SCHEDULED_POWER_ON_DAYS = "nt_scheduled_power_on_days";
        public static final String NT_SCHEDULED_POWER_ON_H = "nt_scheduled_power_on_h";
        public static final String NT_SCHEDULED_POWER_ON_M = "nt_scheduled_power_on_m";
        public static final String NT_SCHEDULED_POWER_ON_TIME = "nt_scheduled_power_on_time";
        public static final String NT_SCREEN_CALIBRATION_MODE = "nt_screen_calibration_mode";
        public static final String NT_SCREEN_HEIGHT = "nt_screen_height";
        public static final String NT_SCREEN_ON_WHILE_NOTIFICATION = "nt_screen_on_while_notification";
        public static final String NT_SCREEN_SAVE_MODE = "nt_screen_save_mode";
        public static final String NT_SCREEN_WIDTH = "nt_screen_width";
        public static final String NT_SET_WALLPAPER_SIMULTANEOUSLY = "set_wallpaper_simultaneously";
        public static final String NT_SHOPDEMO_TOOL_MUSIC = "nt_shopdemo_tool_music";
        public static final String NT_SHOPDEMO_TOOL_MUSIC_VOLUME = "nt_shopdemo_tool_music_volume";
        public static final String NT_SHOPDEMO_TOOL_PASSWORD = "nt_shopdemo_tool_password";
        public static final String NT_SHOPDEMO_TOOL_PLAYTIME = "nt_shopdemo_tool_playtime";
        public static final String NT_SHOPDEMO_TOOL_PLAYTIME_END = "nt_shopdemo_tool_playtime_end";
        public static final String NT_SHOPDEMO_TOOL_PLAYTIME_END_DEFAULT_VALUE = "2200";
        public static final String NT_SHOPDEMO_TOOL_PLAYTIME_START = "nt_shopdemo_tool_playtime_start";
        public static final String NT_SHOPDEMO_TOOL_PLAYTIME_START_DEFAULT_VALUE = "0900";
        public static final String NT_SHOPDEMO_TOOL_PLAYVIDEO = "nt_shopdemo_tool_playvideo";
        public static final String NT_SHOWS_NOTIFICATION_ON_LAUNCHER = "nt_shows_notification_on_launcher";
        public static final String NT_SHOW_ACCESS_PASSWORD = "nt_show_access_password";
        public static final String NT_SHOW_ALARM = "nt_show_alarm";
        public static final String NT_SHOW_HD = "nt_show_hd";
        public static final String NT_SHOW_HEADSET = "nt_show_headset";
        public static final String NT_SHOW_MTP_NOTIFICATION = "nt_show_mtp_notification";
        public static final String NT_SHOW_USER_GUIDE = "nt_show_user_guide";
        public static final String NT_SHOW_VOLUME = "nt_show_volume";
        public static final String NT_SMARTBAR_AUTO_HIDE = "nt_smartbar_auto_hide";
        public static final String NT_SMARTBAR_HEIGHT_VALUE = "nt_smartbar_height_value";
        public static final String NT_SMARTBAR_HIT_EDGE_COUNT_INSIDE = "nt_smartbar_hit_edge_count_inside";
        public static final String NT_SMARTBAR_HIT_EDGE_COUNT_OUTSIDE = "nt_smartbar_hit_edge_count_outside";
        public static final String NT_SMARTBAR_PADDING = "nt_smartbar_padding";
        public static final String NT_SMARTBAR_PADDING_VALUE = "nt_smartbar_padding_value";
        public static final String NT_SMART_TOUCH_BACK_DISABLE = "nt_float_touch_enable";
        public static final String NT_SMART_TOUCH_BEHAVIOR_ALPHA = "nt_smart_touch_behavior_alpha";
        public static final String NT_SMART_TOUCH_BEHAVIOR_CLICK = "nt_smart_touch_behavior_click";
        public static final String NT_SMART_TOUCH_BEHAVIOR_DOUBLECLICK = "nt_smart_touch_behavior_doubleclick";
        public static final String NT_SMART_TOUCH_BEHAVIOR_DOWN = "nt_smart_touch_behavior_down";
        public static final String NT_SMART_TOUCH_BEHAVIOR_LEFTRIGHT = "nt_smart_touch_behavior_leftright";
        public static final String NT_SMART_TOUCH_BEHAVIOR_LONG = "nt_smart_touch_behavior_long";
        public static final String NT_SMART_TOUCH_BEHAVIOR_UP = "nt_smart_touch_behavior_up";
        public static final String NT_SMART_TOUCH_CHANGE = "nt_smart_touch_change";
        public static final String NT_SMART_TOUCH_SWITCH = "nt_smart_touch_switch";
        public static final String NT_SMART_VOICE_WAKEUP_BY_VOICE = "nt_smart_voice_wakeup_by_voice";
        public static final String NT_STATUS_BAR_TINT = "nt_status_bar_tint";
        public static final String NT_SWITCHER_RECENTS_ENABLE = "nt_navigation_bar_switcher_recents";
        public static final String NT_TAPDET_SENSOR_ENABLE = "nt_tapdet_sensor_enable";
        public static final String NT_TAPDET_SENSOR_MODE = "nt_tapdet_sensor_mode";
        public static final String NT_TIMES_OF_BOOT_COMPLETED = "nt_times_of_boot_completed";
        public static final String NT_USE_NT_COMMUNICATION = "nt_use_NT_communication";
        public static final String NT_USE_NT_NAVIGATION_BAR = "nt_use_NT_navigation_bar";
        public static final String NT_VERSION_SETTING_UP = "NT_version_setting_up";
        public static final String NT_VIBRATOR_ALARM_RINGTONE_EFFECTID = "NT_alarm_ringid";
        public static final String NT_VIBRATOR_NOTIFICATION_RINGTONE_EFFECTID = "NT_notification_ringid";
        public static final String NT_VIBRATOR_TELE_RINGTONE_EFFECTID = "NT_phone_ringid";
        public static final String NT_WEEK_START = "week_start";
        public static final String NT_WINDOW_MODE_SYSTEM_KEYBOARD = "nt_window_mode_system_keyboard";
        public static final String NT_WIRELESS_REVERSE_CHARGE = "nt_wireless_reverse_charge";
        public static final String POWER_DOUBLE_CLICK = "power_double_click";
        public static final String PRESSKEY_FEEDBACK_INTENSITY = "presskey_feedback_intensity";
        public static final Set<String> PUBLIC_SETTINGS;
        public static final String RAISEWAKEUP_SWITCH = "raisewakeup_switch";
        public static final String REJECT_WHEN_OUTOF_PHONEBOOK = "reject_when_outof_phonebook";
        public static final String REJECT_WHEN_UNKOWN_UNMBER = "reject_when_unkown_number";
        public static final String REVERSE_CHARGING_LIMITING_LEVEL = "reverse_charging_limiting_level";
        public static final String RINGTONE_SET_FLAG = "ringtone_set";
        public static final String RINGTONE_SOUND_FILE_PATH = "ringtone_sound_file_path";
        public static final String RINGTONE_SOUND_PHONE_1_SET_FLAG = "ringtone_sound_phone_1_set";
        public static final String RINGTONE_SOUND_PHONE_2_SET_FLAG = "ringtone_sound_phone_2_set";
        public static final String SCREENSHOT_SOUNDS_ENABLED = "screenshot_sounds_enabled";
        public static final String SCREEN_BRIGHTNESS_ANIMATION = "animation_brightness";
        public static final String SCREEN_BRIGHTNESS_PREFERED = "prefer_screen_brightness";
        public static final String SCREEN_LUX_PREFERED = "prefer_screen_lux";
        public static final String SHOW_NAVIGATION_BAR = "nt_show_navigation_bar";
        public static final String SNS_ENALBE = "sns_enable";
        public static final String SOUND_SPDIF = "sound_spdif";
        public static final String SOUND_SPDIF_BUTTON = "sound_spdif_button";
        public static final String SPAM_CALL_FILTER_ENABLE = "spam_call_filter_enable";
        public static final String SPAM_CALL_FILTER_FROM_CLOUD_LEVEL = "spam_call_filter_from_cloud_level";
        public static final String STATUSBAR_BATTERY_PERCENT = "statusbar_battery_percent";
        public static final String STATUSBAR_BATTERY_STYLE = "statusbar_battery_style";
        public static final String SUBSCREEN_CAMERA = "subscreen_camera";
        public static final String SUBSCREEN_DOUBLE_CLICK_WAKEUP = "subscreen_double_click_wakeup";
        public static final String SUBSCREEN_PEDOMETER = "subscreen_pedometer";
        public static final String SUBSCREEN_SCREEN_CAPTURE = "subscreen_screen_capture";
        public static final String SUBSCREEN_SCREEN_NOTIFICATION = "subscreen_notification";
        public static final String SUBSCREEN_SCREEN_NOTIFICATION_INCOMING_CALL = "subscreen_notification_incoming_call";
        public static final String SUBSCREEN_SCREEN_NOTIFICATION_PHONE_STATUS = "subscreen_notification_phone_status";
        public static final String SUBSCREEN_SCREEN_NOTIFICATION_REMIND = "subscreen_notification_remind";
        public static final String SUBSCREEN_SCREEN_NOTIFICATION_SOURCE = "subscreen_notification_source";
        public static final String SUBSCREEN_SWITCH = "subscreen_switch";
        public static final String SUBSCREEN_TAKE_PHOTO = "subscreen_take_photo";
        public static final String SUBSCREEN_TURN_OVER_TO_WAKE = "subscreen_turn_over_to_wake";
        public static final String SUBSCREEN_WEATHER = "subscreen_weather";
        public static final String SUB_DISPLAY_SCREEN_BRIGHTNESS = "sub_display_screen_brightness";
        public static final String SUB_DISPLAY_SCREEN_OFF_TIMEOUT = "sub_display_screen_off_timeout";
        public static final String SUB_POINTER_LOCATION = "sub_pointer_location";
        public static final String SUPER_STEREO_SOUND = "super_stereo_sound";
        public static final String VOICE_ASSISTENT_USE_IN_LOCKSCREEN = "voice_assistent_use_in_lockscreen";
        public static final String WELLCOME_PAGE_VERSION_STRING = "wellcome_page_version";
        public static final String RINGTONE_SOUND_PHONE_1 = "ringtone_sound_phone_1";
        public static final Uri DEFAULT_RINGTONE_PHONE_1_URI = Settings.System.getUriFor(RINGTONE_SOUND_PHONE_1);
        public static final String RINGTONE_SOUND_PHONE_2 = "ringtone_sound_phone_2";
        public static final Uri DEFAULT_RINGTONE_PHONE_2_URI = Settings.System.getUriFor(RINGTONE_SOUND_PHONE_2);
        public static final String RINGTONE_SOUND_PHONE_1_CACHE = "ringtone_sound_phone_1_cache";
        public static final Uri DEFAULT_RINGTONE_PHONE_1_URI_CACHE = Settings.System.getUriFor(RINGTONE_SOUND_PHONE_1_CACHE);
        public static final String RINGTONE_SOUND_PHONE_2_CACHE = "ringtone_sound_phone_2_cache";
        public static final Uri DEFAULT_RINGTONE_PHONE_2_URI_CACHE = Settings.System.getUriFor(RINGTONE_SOUND_PHONE_2_CACHE);
        public static final String CALENDAR_SOUND_CACHE = "calendar_sound_cache";
        public static final Uri DEFAULT_CALENDAR_SOUND_URI_CACHE = Settings.System.getUriFor(CALENDAR_SOUND_CACHE);
        public static final String EMAIL_SOUND_CACHE = "email_sound_cache";
        public static final Uri DEFAULT_EMAIL_SOUND_URI_CACHE = Settings.System.getUriFor(EMAIL_SOUND_CACHE);
        public static final String MMS_SOUND_CACHE = "mms_sound_cache";
        public static final Uri DEFAULT_MMS_SOUND_URI_CACHE = Settings.System.getUriFor(MMS_SOUND_CACHE);

        static {
            ArraySet arraySet = new ArraySet();
            PUBLIC_SETTINGS = arraySet;
            arraySet.add(NOTIFICATION_INTERCEPTION_AUTO_CLEAR);
            arraySet.add(NOTIFICATION_INTERCEPTION_SHOW_NUMBER);
            arraySet.add(NT_SHOWS_NOTIFICATION_ON_LAUNCHER);
            arraySet.add(NT_BUBBLE_NOTIFICATION);
            arraySet.add(NOTIFICATION_WAKEUP_SCREEN);
            arraySet.add(LOCKSCREEN_PULL_NOTIFICATIONBAR);
            arraySet.add(NT_CURRENT_NETWROK_SPEED);
            arraySet.add(NT_STATUS_BAR_TINT);
            arraySet.add(STATUSBAR_BATTERY_PERCENT);
            arraySet.add(NT_QUICK_WAKEUP_SWITCH);
            arraySet.add(NT_QUICK_WAKEUP_DOUBLE_CLICK);
            arraySet.add(NT_QUICK_WAKEUP_SLIDE_UP);
            arraySet.add(NT_QUICK_WAKEUP_SLIDE_DOWN);
            arraySet.add(NT_QUICK_WAKEUP_SLIDE_LEFT_RIGHT);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_C);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_C_PACKAGE_DETAIL);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_E);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_E_PACKAGE_DETAIL);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_M);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_M_PACKAGE_DETAIL);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_O);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_O_PACKAGE_DETAIL);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_S);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_S_PACKAGE_DETAIL);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_V);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_V_PACKAGE_DETAIL);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_W);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_W_PACKAGE_DETAIL);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_Z);
            arraySet.add(NT_QUICK_WAKEUP_DRAW_Z_PACKAGE_DETAIL);
            arraySet.add(NT_SMART_TOUCH_SWITCH);
            arraySet.add(NT_SMART_TOUCH_BEHAVIOR_ALPHA);
            arraySet.add(NT_SMART_TOUCH_BEHAVIOR_CLICK);
            arraySet.add(NT_SMART_TOUCH_BEHAVIOR_DOUBLECLICK);
            arraySet.add(NT_SMART_TOUCH_BEHAVIOR_LONG);
            arraySet.add(NT_SMART_TOUCH_BEHAVIOR_UP);
            arraySet.add(NT_SMART_TOUCH_BEHAVIOR_DOWN);
            arraySet.add(NT_SMART_TOUCH_BEHAVIOR_LEFTRIGHT);
            arraySet.add(NT_SMART_TOUCH_CHANGE);
            arraySet.add(CLASSIC_MODE);
            arraySet.add(NT_LARGE_LAUNCHER_ICON);
            arraySet.add(BOTTOM_BUTTON_STYLE_PHONE);
            arraySet.add(CLASSIC_MODE_SMS);
            arraySet.add(CLASSIC_MODE_CLOCK);
            arraySet.add(CLASSIC_MODE_EMAIL);
            arraySet.add(CLASSIC_MODE_CALENDAR);
            arraySet.add(CLASSIC_MODE_MEMOS);
            arraySet.add(RINGTONE_SOUND_PHONE_1);
            arraySet.add(RINGTONE_SOUND_PHONE_2);
            arraySet.add(NT_FP_USE_UNLOCK);
            arraySet.add(NT_FIND_PHONE);
            arraySet.add(NT_FIND_PHONE_WIPE_ALL_NOT_VALIDATED);
            arraySet.add(NT_FIND_PHONE_LOCK_TYPE);
            arraySet.add(NT_FIND_PHONE_AUTO_SEND_NUMBER);
            arraySet.add(CPU_L);
            arraySet.add(HOME_DOUBLE_CLICK);
            arraySet.add(POWER_DOUBLE_CLICK);
            arraySet.add(SHOW_NAVIGATION_BAR);
            arraySet.add(NT_EARPHONE_FEEDBACK_ENABLED);
            arraySet.add(KEY_SYSTEM_TIPS_SOUND);
            arraySet.add(MODE_RING_UP);
            arraySet.add(MMS_SOUND);
            arraySet.add(EMAIL_SOUND);
            arraySet.add(CALENDAR_SOUND);
            arraySet.add(RINGTONE_SET_FLAG);
            arraySet.add(NOTIFICATION_SOUND_SET_FLAG);
            arraySet.add(ALARM_ALERT_SET_FLAG);
            arraySet.add(MMS_SOUND_SET_FLAG);
            arraySet.add(EMAIL_SOUND_SET_FLAG);
            arraySet.add(CALENDAR_SOUND_SET_FLAG);
            arraySet.add(RINGTONE_SOUND_PHONE_1_SET_FLAG);
            arraySet.add(RINGTONE_SOUND_PHONE_2_SET_FLAG);
            arraySet.add(DESKTOP_APP_RECOMMEND);
            arraySet.add("NT_alarm_ringid");
            arraySet.add(NT_FORCE_QUICK_REPLY);
            arraySet.add(LOCKSCREEN_SHOW_MUSIC);
            arraySet.add(LOCKSCREEN_SHOW_LUNAR_CALENDER);
            arraySet.add(NT_POWER_LONG_PRESS_VOICE);
            arraySet.add(HEADSET_MIDDLE_KEY_WAKEUP);
            arraySet.add(VOICE_ASSISTENT_USE_IN_LOCKSCREEN);
            arraySet.add(WELLCOME_PAGE_VERSION_STRING);
            arraySet.add(NT_VERSION_SETTING_UP);
            arraySet.add(NT_SHOW_VOLUME);
            arraySet.add(NT_SHOW_ALARM);
            arraySet.add(NT_SHOW_HEADSET);
            arraySet.add(NT_SHOW_HD);
            arraySet.add(STATUSBAR_BATTERY_STYLE);
        }
    }

    /* loaded from: classes2.dex */
    public static final class Secure {
        public static final String APP_CLONE_ENABLED = "nt_app_clone_enabled";
        public static final String APP_CLONE_ENABLED_PACKAGES = "nt_app_clone_eabled_pkgs";
        public static final String CLIPBOARD_RULE_NAME_SETTINGS = "nt_clipboard_rules_";
        public static final String DISPLAY_DC_LIGHT_ENABLE = "nt_display_dc_light_enable";
        public static final String DISPLAY_DENSITY = "display_density";
        public static final String ESE_SMARTMX = "smartmx_ese";
        public static final String FACERECOGNITION_ADDED_DATA = "nt_face_management_added_data";
        public static final String FACERECOGNITION_FACE_SCREEN_BRIGHTNESS = "nt_face_screen_brightness";
        public static final String FACERECOGNITION_FACE_UNLOCK = "nt_face_unlock";
        public static final String FACERECOGNITION_FACE_UNLOCK_APP = "nt_face_unlock_app";
        public static final String FACERECOGNITION_FACE_UNLOCK_DOCUMENT = "nt_face_unlock_document";
        public static final String FACERECOGNITION_FACE_UNLOCK_SCREEN_LAUNCHER = "nt_face_unlock_screen_launcher";
        public static final String FINGERPRINT_ID_GUEST_MODE = "nt_fp_id_guest_mode";
        public static final String FINGERPRINT_ID_SECRETS_MODE = "nt_fp_id_secrets_mode";
        public static final String INSTALLER_SETTINGS = "NT_installer_settings";
        public static final String LOCK_SCREEN_ALLOW_PRIVATE_NOTIFICATIONS_LIST = "nt_face_allow_private_notification";
        public static final String MOTION_TRIGGER_SHOW_FP_ICON = "motion_trigger_show_fp_icon";
        public static final String NFC_PAYMENT_DEFAULT_CAPTION = "nfc_payment_default_caption";
        public static final String NT_APPLOCK_PWD_ASSOCIATE_ACCOUNT = "nt_applock_pwd_associate_account";
        public static final String NT_AVOID_POWER_KEY_MISOPERATION = "avoid_power_key_misoperation";
        public static final String NT_BT_SESSION_STATUS = "nt_bt_session_status";
        public static final String NT_CTS_STATE = "nt_cts_state";
        public static final String NT_CURRENT_POWER_MODE = "nt_current_power_mode";
        public static final String NT_DEVICE_NAME = "nt_device_name";
        public static final String NT_DOC_PWD_ASSOCIATE_ACCOUNT = "nt_doc_pwd_associate_account";
        public static final String NT_DRIVE_MODE = "nt_drive_mode";
        public static final String NT_DRIVE_MODE_BLUETOOTH_DEVICE = "nt_drive_mode_bluetooth_device";
        public static final String NT_DRIVE_MODE_BLUETOOTH_DEVICE_NAME = "nt_driver_mode_bluetooth_device_name";
        public static final String NT_DRIVE_MODE_BLUETOOTH_TRIGGER = "nt_drive_mode_bluetooth_trigger";
        public static final String NT_DRIVE_MODE_INCALL_VOICE = "nt_drive_mode_incall_voice";
        public static final String NT_DRIVE_MODE_INMSG_VOICE = "nt_drive_mode_inmsg_voice";
        public static final String NT_DRIVE_MODE_MUSIC_AUTOPLAY = "nt_drive_mode_music_autoplay";
        public static final String NT_DRIVE_MODE_REJECT_INCALL_MSG = "nt_drive_mode_reject_incall_msg";
        public static final String NT_DRIVE_MODE_REJECT_INCALL_MSG_CONTENT = "nt_drive_mode_reject_incall_msg_content";
        public static final String NT_ENABLE_TETHER_TOTAL = "nt_enable_tether_total";
        public static final String NT_FACE_RECOGNITION_UNLOCK_WITH_MASK = "nt_face_recognition_unlock_with_mask";
        public static final String NT_FINGERPRINT_INDEX_LIST = "nt_fingerprint_index_list";
        public static final String NT_FINGERPRINT_LAST_ENROLLED_INDEX = "nt_fingerprint_last_enrolled_index";
        public static final String NT_FINGERPRINT_NAME_PREFIX = "nt_fingerprint_name_";
        public static final String NT_FORCE_TOUCH_LEVEL_INDEX = "nt_force_touch_level_index";
        public static final String NT_FORCE_TOUCH_SWITCH = "nt_force_touch_switch";
        public static final String NT_GAME_MODE = "nt_game_mode";
        public static final String NT_GAME_MODE_ACCELERATE = "nt_game_mode_accelerate";
        public static final String NT_GAME_MODE_ACCELERATE_FULL = "nt_game_mode_accelerate_full";
        public static final String NT_GAME_MODE_BARRAGE_NOTIFICATIONS = "nt_game_mode_barrage_notifications";
        public static final String NT_GAME_MODE_DISABLE_BOTTOM_SLIDE = "nt_game_mode_disable_bottom_slide";
        public static final String NT_GAME_MODE_DISABLE_MBACK = "nt_game_mode_disable_mback";
        public static final String NT_GAME_MODE_DISABLE_TOP_SLIDE = "nt_game_mode_disable_top_slide";
        public static final String NT_GAME_MODE_DND = "nt_game_mode_dnd";
        public static final String NT_GAME_MODE_ENABLE_ASSISTANT = "nt_game_mode_game_assistant";
        public static final String NT_GAME_MODE_E_SPORT_MODE = "nt_game_mode_e_sport_mode";
        public static final String NT_GAME_MODE_GAME_KEYBOARD = "nt_game_mode_game_keyboard";
        public static final String NT_GAME_MODE_LANDSCAPE_SWIPE_DOWN_WIDTH_FRACTION = "nt_game_mode_landscape_swipe_down_width_fraction";
        public static final String NT_GAME_MODE_LANDSCAPE_SWIPE_UP_WIDTH_FRACTION = "nt_game_mode_landscape_swipe_up_width_fraction";
        public static final String NT_GAME_MODE_SCREEN_HANGUP = "nt_screen_hangup";
        public static final String NT_GAME_MODE_VIBRATOR_LIST = "nt_game_mode_vibrator_list";
        public static final String NT_GAME_MODE_VIBRATOR_SWITCH = "nt_game_mode_vibrator_switch";
        public static final String NT_GAME_VIBRATOR_ENABLED = "game_vibrator_enabled";
        public static final String NT_GAME_VIBRATOR_HOT_AREAS = "game_vibrator_hot_area";
        public static final String NT_GESTURE_PULL_DOWN_ENABLE = "nt_gesture_pull_down_enable";
        public static final String NT_GUEST_MODE_PASSWORD = "nt_guest_mode_password";
        public static final String NT_INPUT_PASSWORD_PROTECTION = "nt_safe_keyboard";
        public static final String NT_INSTALL_PACKAGE_AUTHENTICATION = "nt_package_install_authentication";
        public static final String NT_KEYGUARD_LOCK = "nt_keyguard_lock";
        public static final String NT_KEYGUARD_PICTORIAL_ENABLED = "nt_keyguard_pictorial_enabled";
        public static final String NT_LOCK_SCREEN_BRIGHTNESS = "NT_lock_screen_brightness";
        public static final String NT_NEED_COMPATIBLE_PASSWORD = "nt_need_compatible_password";
        public static final String NT_NFCP2P_DRAG_GUIDE = "nt_nfcp2p_drag_guide";
        public static final String NT_NFCP2P_ON = "nt_nfcp2p_on";
        public static final String NT_NOTIFICATION_REPLY_ASSISTANT_SWITCH = "nt_notification_reply_assistant_switch";
        public static final HashSet<String> NT_NO_SECURE;
        public static final String NT_PASSWORD_FRONT_FOUR = "nt_password_fronts_four";
        public static final String NT_PASSWORD_LENGTH = "nt_password_length";
        public static final String NT_PASSWORD_LENGTH_APPLOCK = "nt_password_length_applock";
        public static final String NT_PASSWORD_LENGTH_DOCUMENT = "nt_password_length_document";
        public static final String NT_PASSWORD_TYPE = "nt_password_type";
        public static final String NT_PASSWORD_TYPE_APPLOCK = "nt_password_type_app_lock";
        public static final String NT_PASSWORD_TYPE_DOCUMENT = "nt_password_type_document";
        public static final String NT_RED_ENVELOPE_ARRIVING_RING_SWITCH = "nt_red_envelope_arrving_ring_switch";
        public static final String NT_RED_ENVELOPE_ASSISTANT_SWITCH = "nt_red_envelope_assistant_switch";
        public static final String NT_RED_ENVELOPE_OPEN_WHEN_UNLOCK = "nt_red_envelope_open_when_unlock";
        public static final String NT_SHUTDOWN_VERIFY_PASSWORD = "nt_shutdown_verify_password";
        public static final String NT_THREE_FINGERS_SCREENSHOT_ENABLED = "three_fingers_screenshot_enabled";
        public static final String PASSWORD_CHILD_MODE = "nt_password_child_mode";
        public static final String PERM_MEDIA_EXIF_LOCATION_SETTINGS = "permission_meida_exif_location_settings";
        public static final String PERM_MEDIA_EXIF_PARAMETERS_SETTINGS = "permission_meida_exif_parameters_settings";
        public static final String PERM_NOTIFICATION_SETTINGS = "permission_notification_settings";
        public static final String SECRETS_MODE_BROWSER_INCOGNITO_MODE = "nt_secrets_browser_incognito_mode";
        public static final String SECRETS_MODE_CAMERA = "nt_secrets_mode_camera";
        public static final String SYSTEM_MODE = "nt_system_mode";

        static {
            HashSet<String> hashSet = new HashSet<>(30);
            NT_NO_SECURE = hashSet;
            hashSet.add(System.NT_SMARTBAR_HIT_EDGE_COUNT_INSIDE);
            hashSet.add(System.NT_SMARTBAR_HIT_EDGE_COUNT_OUTSIDE);
        }
    }
}
